### ISSUE TITLE
Adding the WireGuard/OpenVPN tunnel option

### ISSUE THREAD

**Issue by OceanCentre** [znoxx/tbng2#1]
It will be great if the user could setup the Wireguard/OpenVPN configuration the way that the TOR or I2P will work inside this tunnel.
It will make the usage of your project more flexible and hardened in case you do not want the ISP see and block the TOR usage with DPI, even if it's your own private bridge.

**Comment by znoxx** [comment]
Can you please elaborate, where exactly VPN server and client reside ?
If you are talking about VPS part -- and you are talking about communicating to bridge over vpn -- good news here, no code changes needed. 
You just modify docker-compose to open bridge only on wg0 interface (e.g. by IP). And setup vpn connection on client. 
For tor on client your bridge string will contain not an ip of vps, but wireguard server. And this is it.
But look. If "home isp" can successfully supress connections to tor exit nodes which you received over vpn and private bridge -- tor connection will suffer.
Did i got your proposal right ?
